name: CICD

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 수동 트리거를 위한 추가

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml  # 암호화된 yml 내용을 복호화하여 생성
          find src

      - name: gradlew 권한 수정
        run: chmod +x ./gradlew

      - name: Build with Gradle (Test 제외)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x test

      - name: List build output
        run: |
          pwd
          ls build/libs/

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: build/libs/*.jar

  transfer:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: my-app

      - name: Add EC2 Host Key
        env:
          host: ${{ secrets.REMOTE_SERVER }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $host >> ~/.ssh/known_hosts  

      # SCP로 서버로 전송
      - name: SCP transfer
        env:
          PEM_KEY: ${{ secrets.PEM_KEY }}  # PEM 키를 GitHub Secrets에 저장
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.REMOTE_SERVER }}
          key: ${{ secrets.PEM_KEY }}
        run: |
          pwd
          echo "${{ secrets.PEM_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh-keygen -R $host
          scp -o StrictHostKeyChecking=no -i private_key.pem my-app/*.jar $username@$host:/home/ubuntu/app/

      - name: 원격 서버에서 빌드 결과물 실행
        env:
          PEM_KEY: ${{ secrets.PEM_KEY }}  # PEM 키를 GitHub Secrets에 저장
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.REMOTE_SERVER }}
          key: ${{ secrets.PEM_KEY }}
        run: |
          echo "${{ secrets.PEM_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -i private_key.pem "username@host" "
            JAR_FILE=\$(find $JAR_FILE_PATH -name '*.jar' | head -n 1) &&
            if [ -n \"\$JAR_FILE\" ]; then
              nohup java -jar \"\$JAR_FILE\" > output.log 2>&1 &
            else
              echo 'No JAR file found!'
            fi
          "